name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - run: npx next export
      - run: touch out/.nojekyll
      - run: git config --global user.name 'github-actions[bot]'
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: git checkout -b gh-pages
      - run: git add out/*
      - run: git commit -m "Deploy to GitHub Pages"
      - run: git push origin gh-pages --force
