name: Deploy Next.js Site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Check Git version
      - name: Check Git Version
        run: git --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Update to the version you're using

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Check if 'out/' Exists
        run: |
          if [ ! -d "out" ]; then
            echo "'out/' directory not found, creating it..."
            mkdir out
          else
            echo "'out/' directory exists."
          fi

      - name: Move Build Output to 'out/'
        run: |
          if [ -d "out" ]; then
            mv * out/ && rm -rf out
            echo "Moved build files to 'out/' directory."
          else
            echo "No 'out/' directory found after build. Skipping move."
          fi

      - name: Setup Git with Personal Access Token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/awnonbhowmik/awnonbhowmik.github.io.git

      - name: Commit and Push Changes
        run: |
          # Only commit and push if there are changes
          if [[ $(git status --porcelain) ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Automated deployment from GitHub Actions"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/awnonbhowmik/awnonbhowmik.github.io.git HEAD:main
          else
            echo "No changes to commit. Skipping push."
          fi
